
services:
  app:
    build:
      context: .
    restart: unless-stopped
  db:
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "ingrid_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  ingrid_db: {}
